#!/bin/sh
  
set -e

if [ "$1" = "configure" ]; then
    for file in /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
    do
        orig_file="/usr/share/kali-theme-common/$(basename $file)"
        if [ ! -e $file ] && [ -e $orig_file ]; then
            echo "Installing $orig_file as $file"
            mkdir -p $(dirname $file)
            cp $orig_file $file
        fi
    done
    dconf update || true
fi

#DEBHELPER#
