Backgrounds/* usr/share/backgrounds/
Color-Schemes/* usr/share/
share/* usr/share/
Icon-Theme/* usr/share/icons/
Window-Theme/* usr/share/themes/
Grub-Theme/* boot/grub/themes/
Plymouth-Theme/* usr/share/plymouth/themes/
desktop-base/* usr/share/desktop-base/kali-theme/
kali-logos/* usr/images/kali-logos/
xfce/xsettings.xml usr/share/kali-themes-common/
# Those are created by "make install"
usr/share/icons/
